#!/usr/bin/Rscript
dataFolder=commandArgs(TRUE)[1]
if(is.na(dataFolder)) stop("No data folder specified")
if(!file.exists(dataFolder)) stop("Specified data folder does not exists")

cores=commandArgs(TRUE)[2]
if(is.na(cores)) stop("No number of cores specified")
if(is.na(as.numeric(cores))) stop("The number of cores must be an integer")
cores<-as.numeric(cores)

library('R.matlab')
library('fastICA')
library('foreach')
library('doSNOW')
library('glmnet')
library('tools')

sourceDir <- function(dir) {
  for (f in list.files(dir, full.names=TRUE)) {
    if (file.info(f)$isdir) sourceDir(f)
    else if (file_ext(f) == "R") {
      print(paste("---> Sourcing", f))
      source(f)
    }
  }
}

registerDoSNOW(makeCluster(cores))
sourceDir(getwd())
runCompetition(dataFolder)


