#!/usr/bin/Rscript
dataFolder=commandArgs(TRUE)[1]
if(is.na(dataFolder)) stop("No data folder specified")
if(!file.exists(dataFolder)) stop("Specified data folder does not exists")

cores=commandArgs(TRUE)[2]
if(is.na(cores)) stop("No number of cores specified")
if(is.na(as.numeric(cores))) stop("The number of cores must be an integer")
cores<-as.numeric(cores)

tryCatch({
  source('./src/setupWorkEnviroment.R')
  setupWorkEnvironment(FALSE);
  cl <- makeCluster(cores);
  registerDoSNOW(cl);
  runCompetition(dataFolder);
  }, finally = {
    print("Releasing resources...");
    stopCluster(cl)
  })
